build:
  version: "1.0"

orders:
  message: "Welcome to quick-eats order microservice production APIs "
  contactDetails:
    name: "Oleksand Usyk - Product Owner"
    email: "oleksandr.usyk@ukr.net"
  onCallSupportNumbers:
    - +380 68 123 4567