build:
  version: "1.0"

orders:
  message: "Welcome to quick-eats order microservice production APIs "
  contactDetails:
    name: "Vasilyi Shevchenko - Product Owner"
    email: "vasylyi.shevchenko@ukr.net"
  onCallSupportNumbers:
    - +380 68 123 4567