build:
  version: "3.0"

order-service:
  message: "Welcome to quick-eats order microservice local APIs "
  contactDetails:
    name: "Mykhailo Kornukh - Java Developer"
    email: "mykhailo.kornukh@gmail.com"
  onCallSupport:
    - +380 68 123 4567
