build:
  version: "1.0"

order-service:
  message: "Welcome to quick-eats user microservice production APIs"
  contactDetails:
    name: "Olga Savchenko - Product Owner"
    email: "olga.savchenko@ukr.net"
  onCallSupport:
    - +380 68 123 4567