server:
  port: 8071

spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/alwayswannajava/quick-east-microservice-config"
          timeout: 4
          default-label: main
          clone-on-start: true
          force-pull: true
  application:
    name: "configserver"
  profiles:
    active: git