server:
  port: 8081
mongock:
  migration-scan-package: com.userservice.migration
  enabled: true
spring:
  data:
    mongodb:
      uri: mongodb+srv://mongodbuser:yUBfv7eLbiGoJKVP@cluster0.bgoy1vx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      password: yUBfv7eLbiGoJKVP
      database: users