server:
  port: 8081
mongock:
  migration-scan-package: com.userservice.migration
  enabled: true
spring:
  profiles:
    active: "prod"
  data:
    mongodb:
      uri: {$MONGODB_URL}
      database: users
  config:
    import: "optional:classpath:http://localhost:8071"
  application:
    name: user-service
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  cloud:
    bus:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"