server:
  port: 8081
mongock:
  migration-scan-package: com.userservice.migration
  enabled: true
spring:
  profiles:
    active: "prod"
  data:
    mongodb:
      uri: ${MONGODB_URL}
      database: users
  config:
    import: "optional:configserver:http://localhost:8071/"
  application:
    name: user-service
  cloud:
    stream:
      bindings:
        sendCommunication-out-0:
          destination: send-communication

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  app:
    name: "user-service"
    description: "Quick Eats User Service Application"
    developer: "Mykhailo Kornukh"
    version: "1.0.0"