server:
  port: 8083
spring:
  profiles:
    active: "prod"
  liquibase:
    default-schema: public
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orders?useSSL=false&serverTimezone=UTC
    username: ${POSTRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
        ddl-auto: validate
    show-sql: true
    open-in-view: false
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  cloud:
    bus:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"