server:
  port: 8082
mongock:
  migration-scan-package: com.restarauntservice.migration
  enabled: true
spring:
  profiles:
    active: "prod"
  application:
    name: restaurant-service
  data:
    mongodb:
      uri: ${MONGODB_URL}
      database: restaurants
  config:
    import: "optional:classpath:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  cloud:
    bus:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"